First Commit
piotr-grosicki/project-jdp-2107-01 pull request #19
Opened 2021-07-28 17:11 UTC by oskarferens

Nic na czerwono, aplikacja odpala. Powinno byc ok

2021-07-28 17:30 UTC, piotr-grosicki requested changes
tresc commitow nie powina byc first commit / second commit itd tylko cos co opisze co zostalo dodane w danym commicie

2021-07-28 17:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public ProductDto getProduct (Long id) {
brakuje adnotacji path variable (to zostalo w ogole ustalone z grupa?)

2021-07-28 17:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void createProduct(ProductDto productDto) {
brakuje adnotacji request body

2021-07-28 17:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public ProductDto updateProduct(ProductDto productDto) {
brakuje adnotacji request body

2021-07-28 17:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void deleteTask(Long id) {
brakuje adnotacji path variable (to zostalo w ogole ustalone z grupa?)

2021-07-28 18:52 UTC, takado8 reviewed
hmm tak popatrzyłem i wszyscy używają adnotacji @RequestParam, nigdzie indziej nie widzę podawania parametrów przez @PathVariable, jeśli to w niczym nie przeszkadza, to może lepiej byłoby się trzymać jednego formatu? :) w sumie tego nie ustalaliśmy ale tak wyszło. zerknij do innych controllerów.

2021-07-29 06:23 UTC, piotr-grosicki requested changes
path variable do zmienienia na request variable - nie zostalo to ustalone z grupa

2021-07-29 16:01 UTC, piotr-grosicki approved these changes

2021-07-29 16:01 UTC, merged