CartController implementation
piotr-grosicki/project-jdp-2107-01 pull request #2
Opened 2021-07-21 19:52 UTC by Monika950125

2021-07-21 20:55 UTC, piotr-grosicki requested changes

2021-07-21 20:55 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getProducts(){
tutaj powinno byc troche wiecej metod ;) dodawanie produktu, usuwanie itd, zgodnie z rozpiska w module.

2021-07-21 22:18 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getProducts(){
A cała klasa CartController nie powinna być oznaczona adnotacją @RequestMapping z adresem przyjmowania żądań ?

2021-07-22 06:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getProducts(){
rowniez :)

2021-07-22 15:17 UTC, Monika950125 commented
Metody dodane

2021-07-22 16:17 UTC, piotr-grosicki requested changes

2021-07-22 16:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getProducts() {
to powinno byc pobieranie produktow z koszyka - brakuje parametru wskazujacego z ktorego koszyka

2021-07-22 16:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createCart() {
brakuje dto z koszykiem

2021-07-22 16:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void addProducts(@RequestBody List<ProductDto> products) {
to powinno byc dodawanie produktow do koszyka, brakuje parametru wskazujacego do ktorego koszyka

2021-07-22 16:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void deleteProduct(@RequestParam Integer id) {
to powinno byc usuwanie produktu z koszyka, brakuje parametru wskazujacego z ktorego koszyka

2021-07-22 16:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder() {
brakuje parametru wskazujacego z ktorego koszyka ma powstac zamowienie

2021-07-26 09:26 UTC, closed without merging