Task jdp210701 22
piotr-grosicki/project-jdp-2107-01 pull request #21
Opened 2021-07-29 01:19 UTC by takado8

skończona implementacja GroupControllera. 
drobne poprawki w klasie Product (zmiana nazwy DESC na DESCRIPTION i usunięcie literówki ' w "`GROUP_ID" w celu wyeliminowania błędów przy odpalaniu aplikacji.

2021-07-29 06:24 UTC, piotr-grosicki requested changes

2021-07-29 06:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/group/mapper/GroupMapper.java
> +        return new GroupDto(group.getId(), group.getName(), group.getProducts());
w dto nie powinno byc encji, powinny byc same ich ID wiec `group.getProducts` nie jest poprawnym mapowaniem

2021-07-29 12:19 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupController.java
> +    private final DbService dbService;
Ja wiem, że w sumie po pakietach będzie można dojść do tego, który serwis jest od czego, ale może byłoby czytelniej gdyby każdy serwis w nazwie klasy zawierał swoje pochodzenie ( np GroupDbService ) Bo później będziemy mieć 5 serwisów o takiej samej nazwie i będzie się ciężej połapać
Taki drobny szczegół mi przyszedł na myśl :)

2021-07-29 12:28 UTC, magorska commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupController.java
> +    private final DbService dbService;
Właśnie przed chwilą robiłam D Service do Usera i nazwała UserDbService żebyśmy się nie pogubili, więc myślę że to dobry pomysł :)

2021-07-29 16:14 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupController.java
> +    private final DbService dbService;
macie rację, zmienię to ;)

2021-07-30 01:13 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/mapper/GroupMapper.java
> +    ProductDao productDao;
użyłem tu Dto, bo dBservice jest w trakcie pisania przez kogoś. podmieni się jak będzie gotowe.

2021-08-01 11:00 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupNotFoundException.java
> +import java.util.function.Supplier;
nie uywany import

2021-08-01 11:11 UTC, jaGda requested changes

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
>  @AllArgsConstructor
brak konstruktora bezparametrowego

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/domain/GroupDto.java
> +import com.kodilla.ecommercee.product.domain.Product;
nieużywany import

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupNotFoundException.java
> +import java.util.function.Supplier;
nieużywany import

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/repository/GroupDao.java
> +import com.kodilla.ecommercee.group.domain.GroupDto;
nieużywany import

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/service/GroupDbService.java
> +import com.kodilla.ecommercee.group.domain.GroupDto;
niużywany import

2021-08-01 11:11 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/service/GroupDbService.java
> +import lombok.var;
niużywany import

2021-08-02 17:07 UTC, adrianghub requested changes

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupNotFoundException.java
> +import java.util.function.Supplier;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/service/GroupDbService.java
> +import lombok.var;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/service/GroupDbService.java
> +import com.kodilla.ecommercee.group.domain.GroupDto;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/repository/GroupDao.java
> +import com.kodilla.ecommercee.group.domain.GroupDto;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/controller/GroupNotFoundException.java
> +import java.util.function.Supplier;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/domain/GroupDto.java
> +import com.kodilla.ecommercee.product.domain.Product;
usunięty.

2021-08-02 19:10 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
>  @AllArgsConstructor
dodany.

2021-08-02 19:15 UTC, takado8 commented
zmergowane z maina na świeżo i dodane ww. poprawki.

2021-08-03 17:34 UTC, takado8 commented
nie wiem, otworzę nowy PR dla tego questa, bo jest gotowy od tygodnia i nikt go nie akceptuje :P

2021-08-03 17:34 UTC, closed without merging