Entity Group Test
piotr-grosicki/project-jdp-2107-01 pull request #24
Opened 2021-07-29 19:55 UTC by Monika950125

2021-07-29 22:30 UTC, Paweloz requested changes

2021-07-29 22:30 UTC, Paweloz commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +public class GroupTestSuite {
Hej, tu masz tylko test zapisywania encji do bazy. Brakuje testów pozostałych operacji CRUD i ich wpływu na relację między encjami. Pisałaś, że masz jakieś problemy w Intelij z tymi testami, daj znać jakie to może coś zaradzimy :)

2021-07-29 23:13 UTC, MattStann commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +        Group group = new Group(null, "nazwa_grupy", new ArrayList<>());
Stwórz sobie konstruktor w encji Group z samą nazwą bez id, będzie ci łatwiej tworzyć obiekt grupy, plus ID nie może być nullem więc i ten problem konstruktorem z samą nazwą rozwiążesz.

2021-07-30 18:57 UTC, adrianghub requested changes

2021-07-30 18:57 UTC, adrianghub commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +import com.kodilla.ecommercee.user.repository.UserDao;
Nieużywane importy ;)

2021-07-30 18:57 UTC, adrianghub commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +import java.time.LocalDate;
Nieużywane importy.

2021-07-30 18:57 UTC, adrianghub commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +import java.util.List;
Nieużywane importy.

2021-07-30 18:57 UTC, adrianghub commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +import static org.springframework.test.web.servlet.result.StatusResultMatchersExtensionsKt.isEqualTo;
Nieużywane importy.

2021-07-30 18:57 UTC, adrianghub commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +        long id = group.getId();
Sugerowałbym nie tworzyć nadmiernie zmiennej. Możesz równie dobrze odwołać się do id group bezpośrednio w metodzie deleteById (cleanup).

2021-07-30 19:08 UTC, Monika950125 commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +        Group group = new Group(null, "nazwa_grupy", new ArrayList<>());
Zgodzę się z tym, tylko według mnie w encji adnotacja @AllArgsConstructor w ogóle nie jest potrzebna, ja bym ją usunęła i dopiero wtedy by należało stworzyć konstrukor ręcznie. Ponadto skoro Id ma dnotację @GeneretedValue, to i tak nie ma znaczenia czy ja w piszę null w miejsce id bo ono i tak generowane jest automatycznie

2021-07-30 20:43 UTC, Monika950125 commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +public class GroupTestSuite {
Poprawione

2021-07-30 20:48 UTC, MattStann commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +        Group group = new Group(null, "nazwa_grupy", new ArrayList<>());
Zgodzę się z tym, że adnotacja AllArgsConstructor nie jest potrzebna, tak jak i w innych encjach. Ja przy testach nie usuwałem adnotacji i tworzyłem dodatkowe konstruktory, myślałem, że jak da się null to będzie problem z uruchomieniem testu.

2021-07-30 21:06 UTC, Monika950125 commented on src/test/java/com/kodilla/ecommercee/group/GroupTestSuite.java
> +        Group group = new Group(null, "nazwa_grupy", new ArrayList<>());
To akurat nie przeszkadzało, ale dodałam ten konstruktor bez id, w razie czego adnotację będzie można usunąć później

2021-08-02 17:08 UTC, adrianghub approved these changes

2021-08-02 17:21 UTC, Paweloz requested changes

2021-08-02 17:21 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void deleteTask(@RequestBody Long id) {
Do parametru Long id na pewno poprawnie było z adnotacją @RequestParam, wcześniej miałaś dobrze :)

2021-08-02 17:21 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Nie jestem pewny czy CascadeType.ALL jest bezpieczny. Żeby się nie okazało, że usunięcie produktu usuwa nam również całą grupę i na odwrót. Ja bym to chyba zostawił domyślnie, ale jak w testach wychodziło Ci wszystko poprawnie dla powiązanych encji to okej :)

2021-08-02 17:33 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Właśnie bez tego nie przechodziło testów, dlatego dopisałam

2021-08-02 17:38 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void deleteTask(@RequestBody Long id) {
To było poprawione tylko do testów, a ten PR z poprawką był wysłany później, tylko teraz  kolejność PR mi się nie zgadza...
poprawię to

2021-08-02 21:40 UTC, MattStann commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Na mój rozum, to opcja CascadeType.ALL zapisuje i usuwa tylko rekord z kolumny dołączonej, w przypadku usunięcia regordu z GroupDao. W ProductDao cały czas te produkty istnieją, łatwo to sprawdzić jak napiszesz assertEquals(0, group.getProducts().size());. Przy wykonaniu tego equalsa wciąż pokaże 2 a test nie przejdzie.

2021-08-02 21:45 UTC, MattStann approved these changes

2021-08-03 00:10 UTC, MattStann commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Długo myślałem, i chyba powinno być CascadeType.REMOVE samo, i w tedy przy usunięciu grupy, rzeczywiście usuwamy produkty, natomiast usuwając produkty, nie usuwamy grupy.

2021-08-03 00:33 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
nie chcemy usuwać produktów z bazy po usunięciu grupy. Produkty są gdzieś w tabeli PRODUCTS a grupa się do nich odnosi. jak usuniemy grupę razem z produktami, to usuniemy produkty które są też w zamówieniach, koszykach itd.
usunięcie grupy powinno usunąć tylko grupę, usunięcie produktu tylko produkt.

2021-08-03 00:47 UTC, MattStann commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Sugerowałem się nazwą testu:  testShouldProductsBeDeletedWhenDeletingGroup, ale rzeczywiście nie możemy usunąć grupy razem z produktami, w ogóle nie powinniśmy usuwać grup, nawet w endpoincie nie mamy możliwości usuwania grupy, jedynie jej aktualizacje.

2021-08-03 10:02 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
No to w takim układzie testShouldProductsBeDeletedWhenDeletingGroup jest zbędny i trzeba by było usunąć cascade i zrobić testShouldProductsPersistWhenDeletingGroup

2021-08-03 12:54 UTC, MattStann commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
W takim wypadku, przy teście testShouldProductsPersistWhenDeletingGroup, Cascade powinien być ustawiony na persist by móc zapisywać rekordy kaskadowo.

2021-08-03 15:09 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
A potrzebujemy zapisywać rekordy kaskadowo ?  W sensie po co zapisując grupe mamy od razu zapisywać product ? Równie dobrze możemy stworzyć pustą grupę, bo przy zapisywaniu każdego produktu i tak podajemy groupId do której ma być on zapisany.

2021-08-03 16:12 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Moim zdaniem nie powinno być produktów bez kategorii (grupy), dlatego chciałam aby przy usunięciu grupy usuwane były też produkty.
A druga sprawa: to jeżeli nie możemy usuwać grup (bo nie ma do tego endpointu), to ja kasuję te dwa testy i zostawiam jedynie zapis i aktualizację grupy

2021-08-03 19:50 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
Tyle, że test encji zakłada sprawdzenie operacji CRUD, czyli między innymi usuwanie rekordów, a test endpointów to jeszcze co innego i jedno nie wyklucza drugiego. To, ze nie mamy endpointów do kasowania grup, to nie znaczy, że operacja usuwania grupy ma nam walić błędy i posypać bazę danych. 
Przeoczyłem w dyskusji tą kwestię z usuwaniem grup i brakiem endpointów, ale myślę, że już mniejsza o to. Jak skasowałaś już te testy, to świat się nie zawali, można to potem dopisać, a pchajmy coś ten projekt do przodu, bo się strasznie zamotaliśmy w tych review i w tyg zmergowaliśmy raptem jednego taska.

2021-08-03 20:21 UTC, MattStann commented on src/main/java/com/kodilla/ecommercee/group/domain/Group.java
> +            cascade = CascadeType.ALL
A czy jeśli usunie się Cascade z Group to testy, z zapisywaniem i aktualizacją przejdą? Bo jeśli tak, to okej można usunąć, jeśli nie to zostawiłbym na persist

2021-08-06 12:09 UTC, Monika950125 commented
Nie można usunąć grupy, bo narusza to constraint w Products - po usunięciu grupy, w produkcie nadal pozostaje Id usuniętej grupy.
Potencjalne rozwiązania:
1. Usunięcie groupId z produktu w trakcie usuwania encji group - funkcjonalność powinna znajdować się w innej warstwie (GroupDbService). Brakuje tam takiej metody, a nie chcę jej dodawać tylko na potrzeby testów
2. Wyrzucenie wyjątku (UnsupportedOperationException) w trakcie próby usunięcia encji group. Spowodowane jest brakiem funkcjonalności usuwania grupy w GroupDbService. 
Wybrałam punkt nr 2, bo według mnie jest to najbardziej logiczne

2021-08-06 22:14 UTC, MattStann approved these changes

2021-08-08 12:13 UTC, Paweloz approved these changes

2021-08-08 20:18 UTC, merged