JDP210701-25 - actual UserController implementation
piotr-grosicki/project-jdp-2107-01 pull request #25
Opened 2021-07-30 08:41 UTC by magorska

Implementacja UserController, poprawiłam też typy zmiennych bo różniły się w User i UserDto.
Zastanawiam się jak wykonać implementację do genereteUserKey

2021-07-30 16:37 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
>      public void blockUser(Long userId) throws UserNotFoundException {
Hej :) Próbuję rozkminić, gdzie w tej metodzie blokujesz użytkownika. Bo tu widzę, że pobierasz użytkownika z bazy, a potem sprawdzasz czy jest już zablokowany i zapisujesz z powrotem tego samego do bazy.
Myślałem, że to będzie coś w stylu, że go pobierasz, sprawdzasz czy jest zablokowany i jak nie jest to wtedy robisz blockedUser.setBlocked( true ) i wtedy zapisujesz ponownie już zablokowanego użytkownika. 
Reszta kodu wygląda dobrze i już miałem kilkać approval, tylko tego jednego nie rozumiem :)

2021-07-30 18:50 UTC, adrianghub requested changes

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
> +//    public void generateUserKey(Long userKey) {
Możemy chyba usunąć ;)

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public void blockUser(@RequestParam Long userId) throws UserNotFoundException {
W jakim przypadku funkcja wyrzuci wyjątek?

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public UserDto generateUserKey(@RequestParam Long userId) throws UserNotFoundException {
W jakim przypadku funkcja wyrzuci wyjątek? (orElseThrow?)

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
>      private List<Order> orders = new ArrayList<>();
Równie dobrze możemy chyba zwrócić pustą listę w metodzie getOrders, bez przypisywania jej do zmiennej.

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
> +import org.springframework.beans.factory.annotation.Autowired;
Niepotrzebny import.

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/mapper/UserMapper.java
> +                userDto.isStatus(),
Nie za bardzo rozumiem, o czym informuje pole isStatus? Pierwsza kwestia to odpowiednia nazwa funkcji, druga to samo pole "status". Określiłbym je może nazwą "active". Co więcej w roocie projektu mamy folder specs i tam do samego pola jest przypisywana wartość "0", bądź "1". Możnaby było pokusić się o typ Enum, ale może też niepotrzebnie w tym przypadku dodaję roboty i odpowiednik w boolean wystarczy. 

Także, jak dla mnie kwestia odpowiedniej nazwy pola.

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
> +import com.kodilla.ecommercee.product.domain.Product;
Niepotrzebny import ;)

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
>  import java.util.Random;
Niepotrzebny import (jeżeli usuniemy kod z komentarza).

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
Możemy przy okazji dodać w konstruktorze przekazany parametr z wiadomością o błędzie ("message").

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
> +        if (blockedUser.isBlocked()) {
Dokładnie, jak wyżej, brakuje setera w metodzie.

2021-07-30 18:50 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
> +    public User generateUserKey(Long userId) throws UserNotFoundException {
(opcjonalnie) Można też pokusić się o skorzystanie z utilsa RandomStringUtils - https://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/RandomStringUtils.html

2021-07-30 19:17 UTC, takado8 requested changes

2021-07-30 19:17 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
> +        String keyGenerateFrom = lowerCase + upperCase + numbers;
cześć :) to mógłby być jeden string od początku zawierający wszystkie znaki :P
Myślę też, że warto by ten generator wydzielić jako osobną klasę.

2021-08-02 18:44 UTC, jaGda submitted a review, later dismissed

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +@RequiredArgsConstructor
@RequiredArgsConstructor generuje konstruktor i inicjalizuje pola final oraz @NotNull - w tym przypadku jest zbędny, chyba, ze pola zrobisz final ale wtedy mozna usunąć @Autowired

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
> +
zbędny odstęp

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
> +    public List<Order> getOrders() {
Ten getter jest niepotrzebny - użyliśmy @Getter z lomboka

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
Czy nie powinno być pola Cart - w projekcie bazy mieliśmy relację 1:1?

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +import java.util.function.Supplier;
nieużywany import

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +    private String message;
niezainicjowane pole - można usunąć albo przekazać do kontruktora

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +package com.kodilla.ecommercee.user.domain;
klasa tworząca wyjątek powinna być w folderze z controlerem

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/mapper/UserMapper.java
> +                user.getOrders());
UserDto nie powinno przechowywać encji

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/mapper/UserMapper.java
> +                userDto.getOrders());
tutaj potrzeba czegoś więcej - tzn. na podstawie Id z repository Order pobrać encję Order

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
> +    private List<Order> orders;
W dto nie powinno być encji

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/repository/UserDao.java
> +    User save(User user);
niepotrzebnie nadpisana metoda

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/repository/UserDao.java
> +    Optional<User> findById(Long userId);
niepotrzebnie nadpisana metoda

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/repository/UserDao.java
> +    void deleteById(Long userId);
niepotrzebnie nadpisana metoda

2021-08-02 18:44 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/service/UserDbService.java
> +    private UserKeyGenerator userKeyGenerator;
obydwa pola powinny być final jeśli @RequiredArgsConstructor ma zadziałać

2021-08-02 20:56 UTC, adrianghub requested changes

2021-08-02 20:56 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/domain/UserKeyGenerator.java
> +    private final String keyGenerateFrom = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
Można oznaczyć zmienną wartością static.

2021-08-02 20:56 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    @GetMapping("/getAllUsers")
Można usunąć slash z endpointu.

2021-08-02 21:18 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
yup

2021-08-02 21:20 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/UserKeyGenerator.java
> +    private final String keyGenerateFrom = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
i nazwać dużymi

2021-08-03 21:06 UTC, takado8 requested changes

2021-08-03 21:06 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
> +    private List<Order> orders;
zgadza się, w dto nie powinno być encji, tylko lista id np. List<Long> ordersIds;

2021-08-03 21:06 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +package com.kodilla.ecommercee.user.domain;
yup

2021-08-03 21:06 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
też jestem za

2021-08-04 22:40 UTC, takado8 requested changes

2021-08-05 17:32 UTC, Paweloz commented
W metodzie blockUser masz 
if (blockedUser.isBlocked()) {
       blockedUser.setBlocked(true);
}

Warunek sprawdza czy użytkownik jest zablokowany i jeśli tak, to próbuje go blokować ponownie. Brakuje tylko ! wewnątrz if i by było dobrze :)

2021-08-05 17:36 UTC, Paweloz approved these changes

2021-08-05 18:01 UTC, magorska commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public void blockUser(@RequestParam Long userId) throws UserNotFoundException {
logika wyrzucenia wyjątku jest w dbService - wyrzuca jesli nie ma użytkownika o danym id

2021-08-05 18:01 UTC, magorska commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public UserDto generateUserKey(@RequestParam Long userId) throws UserNotFoundException {
logika wyrzucenia wyjątku jest w dbService - wyrzuca jesli nie ma użytkownika o danym id

2021-08-05 18:06 UTC, magorska commented on src/main/java/com/kodilla/ecommercee/user/mapper/UserMapper.java
> +                userDto.isStatus(),
myślę, że boolean powinien wystarczyć. Faktycznie nazwa wyszła tu dziwnie przez nazwę pola, ale taka była ustalana od początku

2021-08-05 18:11 UTC, adrianghub approved these changes

2021-08-05 18:29 UTC, MattStann approved these changes

2021-08-05 20:14 UTC, takado8 approved these changes

2021-08-06 09:37 UTC, merged