Task-24 OrderController - rzeczywista implementacja metod
piotr-grosicki/project-jdp-2107-01 pull request #28
Opened 2021-07-31 18:54 UTC by jaGda

2021-07-31 20:19 UTC, takado8 requested changes
zmiany w 25 plikach, wspaniale ;) Wydaję mi się, że sporo pracy byś sobie oszczędziła nie pisząc sama wszystkich mapperów które ktoś właśnie pisze :D po CartMapper np. wystarczyło napisać :P

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    private OrderService service;
umówiliśmy się na standard nazywania serwisów db: PakietDbService eg. OrderDbService orderDbService;

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/order/domain/Order.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
Pownien tu być CascadeType.ALL ? czy przy usuwaniu ordera nie usunie teraz nam produktów z db?

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/domain/Product.java
> +    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
Pownien tu być CascadeType.ALL ?

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/repository/ProductDao.java
> +public interface ProductDao extends JpaRepository<Product, Long> {
umówiliśmy się na CRUD

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/service/ProductService.java
> +public class ProductService {
ProductDBService

2021-07-31 20:19 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
>              fetch = FetchType.LAZY
Pownien tu być CascadeType.ALL ? czy przy usuwaniu Usera nie usunie teraz nam orderów z db?

2021-08-01 06:06 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/repository/GroupDao.java
> +public interface GroupDao extends JpaRepository<Group, Long> {
hmmm przeoczyłem - JpaRepository jest dużo zgrabniejszy nie trzeba się bawić z optionalami.

2021-08-01 11:32 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/group/repository/GroupDao.java
> +public interface GroupDao extends JpaRepository<Group, Long> {
done

2021-08-01 11:34 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/cart/domain/Cart.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
usunąłem, ale tak czy siak osoba implementująca kontroler musi się nad tym pochylić

2021-08-01 11:34 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    private OrderService service;
done

2021-08-01 11:35 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/order/domain/Order.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
done

2021-08-01 11:36 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/product/domain/Product.java
> +    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
done

2021-08-01 11:36 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/product/repository/ProductDao.java
> +public interface ProductDao extends JpaRepository<Product, Long> {
done

2021-08-01 11:36 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/product/service/ProductService.java
> +public class ProductService {
done

2021-08-01 11:40 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
>              fetch = FetchType.LAZY
zostawiam, osoba implementująca controller na pewno zwróci na to uwagę

2021-08-01 18:39 UTC, jaGda commented on src/main/java/com/kodilla/ecommercee/user/domain/User.java
>              fetch = FetchType.LAZY
zostawiam to implementującemu Usera

2021-08-02 17:06 UTC, adrianghub approved these changes

2021-08-02 18:57 UTC, takado8 approved these changes

2021-08-03 15:04 UTC, closed without merging

2021-08-03 15:04 UTC, jaGda commented
...