JDP210701-21.1
piotr-grosicki/project-jdp-2107-01 pull request #29
Opened 2021-08-02 20:09 UTC by oskarferens

New branch where:
- code separated from branch 24
- only the files concerned to JDP210701-21 task are modified
- CartController - initial implementation changed. (used ProductDto constructor which has been changed and stopped working)

2021-08-02 21:06 UTC, adrianghub approved these changes

2021-08-03 00:22 UTC, takado8 requested changes
merguje sobie Twój mapper do swojego zadania, wygląda ok.
może o tym gdzie rzucać errory warto spytać PMa, może to nie jest aż tak ważne i nie trzeba tego przerabiać.

2021-08-03 00:22 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/service/ProductDbService.java
> +        return productDao.findById(id).orElseThrow(ProductNotFoundException::new);
Czytałem właśnie, że Errory powinny być rzucane w warstwie Controllera. serwis powinien zwracać optionala który jest rozpakowywany w controllerze.
https://stackoverflow.com/questions/29731353/what-are-the-best-practices-to-handle-exception-at-controller-service-and-dao-l

2021-08-03 11:24 UTC, Monika950125 requested changes

2021-08-03 11:24 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/product/mapper/ProductMapper.java
> +                groupDao.findById(productDto.getGroupId())
Mapper powiniem zajmować się tylko mapowaniem a nie pobieraniem innych obiektów. Jest to złamanie zasady SRP

2021-08-03 11:24 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/product/mapper/ProductMapper.java
> +    private final GroupDao groupDao;
Mapper nie powinien mieć zależności do Dao

2021-08-03 11:24 UTC, Monika950125 commented on src/main/java/com/kodilla/ecommercee/product/service/ProductDbService.java
> +    public void setProductDao(ProductDao productDao) {
Wstrzykiwanie zależności przez setter nie jest zalecaną praktyką
https://reflectoring.io/constructor-injection/

2021-08-03 21:41 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/domain/ProductDto.java
> +    private double price;
btw jak już zmieniasz typ to może na BigDecimal, jest najodpowiedniejszy do obchodzenia się z pieniędzmi.

2021-08-03 21:43 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/service/ProductDbService.java
> +    public void setProductDao(ProductDao productDao) {
noo, fajniej chyba byłoby dać to jako private final i adnotację z Lomboka np. @RequiredArgsConstructor

2021-08-09 23:26 UTC, takado8 requested changes

2021-08-09 23:26 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/cart/controller/CartController.java
>      public List<ProductDto> getProducts(@RequestParam Long cartId) {
tutaj, poniżej, źle rozwiązałeś konflikt :P to co usunąłeś powinno wrócić, a przywróciłeś niechcący zwracanie fejkowych danych

2021-08-09 23:26 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductNotFoundException.java
> +    private final static String MESSAGE = "Wrong id - does not exist!";
tutaj zostało po staremu nie wyświetla id

2021-08-09 23:26 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/product/service/ProductDbService.java
> +    public Product getProduct(final Long id) {
tutaj jeszcze exception nie mówi jakie id nie istnieje

2021-08-10 17:14 UTC, takado8 approved these changes

2021-08-10 17:21 UTC, magorska approved these changes

2021-08-10 19:48 UTC, Paweloz approved these changes

2021-08-10 20:06 UTC, merged