Jdp210701 24 order method implementation
piotr-grosicki/project-jdp-2107-01 pull request #36
Opened 2021-08-07 10:52 UTC by adrianghub

2021-08-09 13:26 UTC, Paweloz requested changes

2021-08-09 13:26 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    public Order getOrder(@RequestParam Long orderId) {
Tutaj powinien być chyba zwracany OrderDto. No chyba, ze Postman zwróci mi wszystko okej dla obiektu Order, ale nie mogę tego sprawdzić, bo brakuje metody POST

2021-08-09 13:26 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
Tutaj chyba przeoczyłeś implementacje :)

2021-08-09 13:40 UTC, Paweloz requested changes

2021-08-09 13:40 UTC, Paweloz commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    public List<OrderDto> getAllUsers() {
Tutaj nazwa metody jest od czapy, chyba przeszła innego kontrolera

2021-08-10 00:02 UTC, takado8 requested changes

2021-08-10 17:52 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/cart/controller/CartController.java
> +        return new OrderDto(order.getId(), LocalDate.of(2021, 7, 15), BigDecimal.valueOf(cart.getPrice().doubleValue()), null, order.getUser().getId());
Jasne, done :)

2021-08-10 17:53 UTC, adrianghub commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
Tak, dzięki za uwagę ;)

2021-08-10 20:01 UTC, Paweloz approved these changes

2021-08-10 20:02 UTC, Paweloz commented
Jest git, jedyne co to github pokazuje, że są konflikty

2021-08-10 23:03 UTC, takado8 approved these changes
daje approve mimo że pokazuje zawalone testy na  CircleCI bo domyslam się że to problem z maina i po mergu rozwiązania Pawła bedzie git.

2021-08-11 13:56 UTC, closed without merging

2021-08-11 13:56 UTC, adrianghub commented
To correct.