Jdp210701 36
piotr-grosicki/project-jdp-2107-01 pull request #37
Opened 2021-08-07 21:02 UTC by adrianghub

Mentions https://projects.kodilla.com/browse/JDP210701-36

2021-08-09 13:31 UTC, Paweloz approved these changes
Chyba Ci się tutaj część zmian pokrywa z poprzednim PR, ale jeśli chodzi o taska 36 z konstruktorami encji User, to wygląda wszystko git :)

2021-08-10 00:11 UTC, takado8 requested changes

2021-08-10 00:11 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/cart/controller/CartController.java
> +        return new OrderDto(order.getId(), LocalDate.of(2021, 7, 15), BigDecimal.valueOf(cart.getPrice().doubleValue()), null, order.getUser().getId());
dto zwracane jest ze stałą datą zamiast tą z orderu, przeoczyłem też jak implementowałem, żeby dodać produkty z carta do orderu tworząc go, jakbym mógł o to poprosić. A potem z orderu zwrócić je w dto zamiast nulla

2021-08-10 00:11 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    public List<OrderDto> getAllUsers() {
pomyłka w nazwie metody

2021-08-10 00:11 UTC, takado8 commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    public Order getOrder(@RequestParam Long orderId) {
tu powinien być zwracany dto

2021-08-10 17:03 UTC, adrianghub commented
> Chyba Ci się tutaj część zmian pokrywa z poprzednim PR, ale jeśli chodzi o taska 36 z konstruktorami encji User, to wygląda wszystko git :)

Aj ;d Dokładnie, dzięki

2021-08-10 17:06 UTC, closed without merging