Added entity Order and repository OrderDao
piotr-grosicki/project-jdp-2107-01 pull request #5
Opened 2021-07-25 18:57 UTC by jaGda

2021-07-25 20:16 UTC, Paweloz reviewed
Wydaje mi się, że CascadeType.ALL nam się w zasadzie nie przyda za bardzo w tym projekcie, bo np w tym przypadku spowoduje, że usunięcie zamówienia będzie skutkowało też usunięciem produktów z bazy. Podobnie z koszykiem. Ja bym chyba do tego żadnych kaskad nie stosował

2021-07-26 06:28 UTC, piotr-grosicki requested changes
konflikty

2021-07-26 20:27 UTC, piotr-grosicki requested changes

2021-07-26 20:27 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/domain/Product.java
> +//    @ManyToMany
czemu to jest zakomentowane? nie trzymamy zakomentowanego kodu w repozytorium

2021-07-27 06:42 UTC, piotr-grosicki requested changes
konflikty

2021-07-27 17:49 UTC, piotr-grosicki requested changes
konflikty

2021-07-28 06:39 UTC, piotr-grosicki requested changes
konflikty

2021-07-28 15:00 UTC, piotr-grosicki approved these changes

2021-07-28 15:00 UTC, merged